### PR TITLE
Created HTML and CSS files

### PR DESCRIPTION
**Pull request by Kanyorok**
Created a new branch and semantically named it Created_HTML/CSS_Files

### CODE REVIEW

**Review by LionRouge1 — CHANGES_REQUESTED** [review]
Hi @Kanyorok, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

almost

## Suggested changes :recycle: 

- [ ] [As mentioned by the previous reviewer](https://github.com/Kanyorok/Module1-Hello_World/pull/1#discussion_r1176639402), Kindly use this recommended Microverse [README template](https://github.com/microverseinc/readme-template) for this project and all projects that you would do in Microverse. When adopting this template, kindly do the following:

- Remove the Microverse logo. If you have your logo, you can use it, otherwise, I would advise you to remove the logo. :+1:

- Personalize the project name and project summary to the name of your project and a summary of what you implemented. :+1:

- Remove all placeholder texts that describe what should be done in each section sunglasses

- In the _**Tech stack section of the README**_, kindly remove the technologies listed in the Client, Server and Database subsections. Those sections contain technologies that were not used in this project. Kindly remove the Server and Database subsections and replace those in the Client subsections with HTML and CSS. :+1: :sunglasses:

- In the _**Key Features section**_, kindly add 1-3 things that you accomplished in this project. I would also advise you to get used to adding these features because you would do that for every project in Microverse and possibly in the professional world. :+1:

- If you are not required to deploy the application, you can remove the _**Live Demo section of the README.md**_ file. If you are required to deploy, then the link to the deployed project should be pasted under this section. :+1:

- In the _**Getting Started**_ Section, kindly do the following for the subsections:

  - In the -**Prerequisite subsection**_, kindly add packages or applications that would be needed to start this application on the local machine. You can include NPM, a browser, a code editor, git and any other thing you can think of. +1
  - In the _**Setup subsection**_, kindly include ways to clone this project and change the directory to the directory of the project. See the example below as a guide:
  ```sh
  cd my-folder
  git clone git@github.com:myaccount/my-project.git
  cd my-project
  ```
- In the _**Install subsection**_, you can indicate ways to install the linters locally and also to run them locally. :+1: :sunglasses:
- The _**Usage subsection**_ should contain ways to run the project in the browser if while the Run tests subsections should contain the commands for running the tests written in the project. +1 sunglasses
- The _**Authors**_ section should contain the social media handles of the owner of the repository and all other collaborators
- The _**Future Features**_ section of the README.md file. The Future Features section should contain 1-3 features that can be implemented in the future. Most times, this section acts as a reference to you and future collaborators whenever you want to improve your projects in the future computer :sunglasses:
- The Show Your Support Section should communicate to people ways they can help advance the project or give a star to the project if they like it :+1: :sunglasses:
- The _**Acknowledgement**_ section should contain information, links and appreciation for those who spurred or contributed to the success of the project :computer:
- The FAQ section is the only optional section and it should contain frequently asked questions about the project and answers to those questions :sunglasses: :+1:
- The LICENSE section should contain permissions given as regards the use of the project. I would advise you to follow the guide on the right side of the article that I would paste below to set a valid LICENSE :+1:
https://choosealicense.com/licenses/mit/

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hello @Kanyorok      👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done so far,  However, there are a few you need to work on, to move to the next project. 💯

 


# Required Changes ♻️

- [ ]  You've not made changes from the last review made by the previous reviewer, so I'll restate the points he asked as it's important to get you approved 👍 

## Changes as requested by the previous reviewer and my suggestion

-  Kindly use this recommended Microverse [README template](https://github.com/microverseinc/readme-template) for this project and all projects that you would do in Microverse. When adopting this template, kindly do the following:

- Remove the Microverse logo. If you have your logo, you can use it, otherwise, I would advise you to remove the logo. 👍

- Personalize the project name and project summary to the name of your project and a summary of what you implemented. 👍

- Remove all placeholder texts that describe what should be done in each section sunglasses

- In the Tech stack section of the README, kindly remove the technologies listed in the Client, Server and Database subsections. Those sections contain technologies that were not used in this project. Kindly remove the Server and Database subsections and replace those in the Client subsections with HTML and CSS. 👍 😎

- In the Key Features section, kindly add 1-3 things that you accomplished in this project. I would also advise you to get used to adding these features because you would do that for every project in Microverse and possibly in the professional world. 👍

- If you are not required to deploy the application, you can remove the Live Demo section of the README.md file. If you are required to deploy, then the link to the deployed project should be pasted under this section. 👍

- In the Getting Started Section, kindly do the following for the subsections:

- The Future Features section of the README.md file. The Future Features section should contain 1-3 features that can be implemented in the future. Most times, this section acts as a reference to you and future collaborators whenever you want to improve your projects in the future computer 😎

- The Show Your Support Section should communicate to people ways they can help advance the project or give a star to the project if they like it 👍 😎

- The Acknowledgement section should contain information, links and appreciation for those who spurred or contributed to the success of the project 💻

- The FAQ section is the only optional section and it should contain frequently asked questions about the project and answers to those questions 😎 👍

- The LICENSE section should contain permissions given as regards the use of the project. I would advise you to follow the guide on the right side of the article that I would paste below to set a valid LICENSE 👍
https://choosealicense.com/licenses/mit/


# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Kanyorok** [comment]
@Shedrack-Sunday 
Hello, I have already fixed all the issues with the README.md file. I did not understand which part is missing. Please, can you be more specific?

**Comment by Shedrack-Sunday** [comment]
> @Shedrack-Sunday Hello, I have already fixed all the issues with the README.md file. I did not understand which part is missing. Please, can you be more specific?

Hello @Kanyorok. The changes you made are in your main branch. Copy the README change there and add it to this branch

**Review by AbelG101 — APPROVED** [review]
# Hi @Kanyorok  👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title ✔

## Optional suggestions
- The next time please make sure you don't directly commit to the `main` branch as this could cause inconsistencies in your project and set you back days if not weeks when building a larger project. ✔

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
